version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OUTLOOK_CLIENT_ID=your_actual_outlook_client_id
      - OUTLOOK_CLIENT_SECRET=your_actual_outlook_client_secret
      - OUTLOOK_REDIRECT_URI=http://localhost:3000/auth/outlook/callback
      - PORT=3000
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: email-client-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9201:9200"  # Changed to avoid conflict
      - "9301:9300"  # Changed to avoid conflict
